In [1]:
!pip install numpy

In [2]:
import numpy as np
import time 

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [158]:
# to checking the performance time of python list and numpy

size = 1_000_000 # we take this big number for comparison 

# python list
py_list = list(range(size))
start = time.time() # it show the start time
sq_list =[ x**2 for x in py_list] # write in form of list comprehension
end = time.time() # it show the end time
print(f"python list time ={end - start} seconds") # different in time for python list

# now we are going to do same thing for numpy array
np_arr = np.array(py_list)
start = time.time()
sq_list =np_arr ** 2 # here in case of numpy we do not need write loop just like in python , in case has there own square
end = time.time()
print(f"numpy array time ={end - start} seconds") # this for numpy array

python list time =0.08168148994445801 seconds
numpy array time =0.02569413185119629 seconds


In [33]:
# memory
import sys

# python list memory occupation size
print(f"python list size ={sys.getsizeof(py_list) * len(py_list)} bytes")

# numpy array memory occupation size
print(f"numpy array size ={np_arr.nbytes} bytes") # in numpy we use nbytes for memory size

python list size =8000056000000 bytes
numpy array size =4000000 bytes


In [34]:
# numpy is homogenerous
arr = np.array([1,2,3,4,5])
print(arr) # here in output we see only int becuase it only data type 
print(type(arr))

arr2 = np.array([1,2,3,4,5 ,"prime"])
print(arr2) # what we see here in output the all item are convert into string"". it alway convert them into one type of data such as string
print(type(arr2)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime']
<class 'numpy.ndarray'>


In [35]:
# numpy is homogenerous
arr = np.array([1,2,3,4,5])
print(arr) # here in output we see only int becuase it only data type 
print(type(arr), arr.dtype)

arr2 = np.array([1,2,3,4,5 ,"prime"])
print(arr2) # what we see here in output the all item are convert into string"". it alway convert them into one type of data such as string
print(type(arr2), arr2.dtype) # here dtype is show the data type

[1 2 3 4 5]
<class 'numpy.ndarray'> int32
['1' '2' '3' '4' '5' 'prime']
<class 'numpy.ndarray'> <U11


In [36]:
# numpy is homogenerous
arr = np.array([1,2,3,4,5])
print(arr) # here in output we see only int becuase it only data type 
print(type(arr), arr.shape) # shape is show the dimension , it means item number size

arr2 = np.array([1,2,3,4,5 ,"prime"])
print(arr2) # what we see here in output the all item are convert into string"". it alway convert them into one type of data such as string
print(type(arr2), arr2.shape ) # shape is show the dimension , it means item number size

[1 2 3 4 5]
<class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime']
<class 'numpy.ndarray'> (6,)


In [37]:
# numpy is homogenerous
arr = np.array([1,2,3,4,5])
print(type(arr), arr.shape) # shape is show the dimension , it means item number size

arr2 = np.array([1,2,3,4,5 ,"prime"])
print(type(arr2), arr2.shape ) # shape is show the dimension , it means item number size

arr2D  = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # it should be proper dimension number of row and column in one array should equal
print(arr2D, arr2D.shape) # shape show the number of row and column

<class 'numpy.ndarray'> (5,)
<class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [38]:
# numpy array create
arr1 = np.zeros((2,3),dtype = "int64") # prefill with 0 value becuase it written zeros
print(arr1, arr1.shape)

arr2 = np.ones((2,3)) # prefill with 1 value , written 1
print(arr2,arr2.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [45]:
# numpy array create
arr1 = np.zeros((2,3),dtype = "int64") # prefill with 0 value becuase it written zeros
print(arr1, arr1.shape)

arr2 = np.ones((2,3)) # prefill with 1 value , written 1
print(arr2,arr2.shape)

arr3 = np.full((3,4),100) # prefilll with value 100
print(arr3,arr3.shape)

arr4 = np.eye(3)  # identity matrix it for showing value 1 in middle diagonal and other 0
print(arr4,arr4.shape)

# i do not know why these code are not running
# arr5 = np.arrange(1,11) # array with 1 to 10 value 
# print(arr5,arr5.shape)

# arr6 = np.arrange(1,11,2) # array with 1 to 10 value 
# print(arr6,arr6.shape)

arr7 = np.linspace(1, 100, 4) # array has only 4 element between 1 to 100
print(arr7, arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[  1.  34.  67. 100.] (4,)


In [47]:
# properties
arr = np.array([1,2,3,4,5]) # one D- array
print(arr.shape)

(5,)


In [52]:
# properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) # two D- array of 3 
print(arr.shape)
print(arr.size)  # total number of element is 9
print(arr.dtype)
print(arr.ndim) # total number of dimension

float_arr = arr.astype(np.float64) # it mean that it converted above int array into float array
print(float_arr, float_arr.dtype)

(3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [59]:
# operation on array 
arr = np.array([[1,2,3],[4,5,6]]) # two cross three size array this is 2 row and 3 column
print(arr,arr.shape) 

reshaped = arr.reshape((3,2)) # this we change the dimension to new dimension (3,2) 3 is row and 2 is column
print(reshaped,reshaped.shape)

flattened = arr.flatten() # 20 => 10 this one D- array it means one row only
print(flattened ,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [61]:
# indexing , it means the cetain element in array
arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[3])

1
4


In [65]:
# indexing  
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])  # 0 row main second wala element , if row and and column you can understand it

3


In [64]:
# fancy indexing 
arr = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [67]:
# boolean indexing  it filter out the greater then value 
arr = np.array([1,2,3,4,5])

print(arr[arr>2])
print(arr[arr % 2==0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [70]:
# slicing (start,end , step )
arr = np.array([1,2,3,4,5])

print(arr[1:4]) # (start,end , step )
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2]) 

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [78]:
# copy vs view 
# copy is made by python_list and it take time and storage whereas view is made by numpy array is not taking as much as space as compare to python copy
# this below is python copy

# nums= [1,2,3,4,5]
# sub_list = nums[1:3]

# sub_list[0] = 200 # here it store in only in sub_list as copy by creating the new
# print(sub_list) #  it store the value 200 as
# print(nums)

# this below is array view
arr = np.array([1,2,3,4,5])
sub_list = arr[1:3] # if we want create copy also in array then we can .copy()
print(sub_list) 

sub_list[0] = 200 # it is not only store in sub_list but ,in original array so ,it show that it do not create copy to any more space
print(sub_list) #  it store the value 200 as 
print(arr)

[2 3]
[200   3]
[  1 200   3   4   5]


In [83]:
# Data types
# int32
arr = np.array([1,2,3,4,5])

print(arr, arr.dtype)

[1 2 3 4 5] int32


In [84]:
# Data types
# float
arr = np.array([1,2,3,4.2,5]) # it show the data type as float because one is 4.2 the, it will so all the value as float type

print(arr, arr.dtype)

[1.  2.  3.  4.2 5. ] float64


In [86]:
arr = np.array([3+5j])
print(arr,arr.dtype)

[3.+5.j] complex128


In [88]:
arr1 = np.array([3+5j])
arr2 = np.array([1+2j])
print(arr1-arr2)
print(arr1+arr2)

[2.+3.j]
[4.+7.j]


In [89]:
arr = np.array(["prime",{1,2,3},3.14]) # here we written the different type of data but in numpy it not treat any type ,but it show as object all together
print(arr,arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [90]:
# multi - dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [104]:
# multi - 2Darray dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D,axis =0)  # it sum of the simple columns of each there 3 column such as(1,4,7)
print(sum_of_columns)

sum_of_row = np.sum(arr2D,axis = 1) # it means it sum the row of 3 three line such as(1,2,3)
print(sum_of_row)

# slicing of 2D array
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [116]:
# 3D array
arr3D = np.array([[[1,2],[3,4],[5,6]],
                  [[7,8],[9,10],[11,12]]])  # # 2 x 3x 2

print(arr3D)
print("Shape:", arr3D.shape)

# indexing
print(arr3D[0,1,1])  #   0 layer , 1st row , 1st column
print(arr3D[1,1,0])  # 1 layer , 1st row , 0st column

# slicing
print(arr3D[:, 0, :])  # take 0th row from all blocks ( (:) it means select all layer 0st row and with 0st column
print(arr3D[:, :, 0]) # ( (:) is select all , (:) is select all row, 0 is select 0 column it first column

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [117]:
# if we want replace this 
(arr3D[:, 0, :]) = 99 # first row from both layers , now we replace the first row of both layer with 99
print(arr3D)

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [118]:
#  vectorization

arr = np.array([1,2,3,4,5]) 
print(arr ** 2) # here we use the square the array number but , in case of python it is done loop for list it lost of time and space

[ 1  4  9 16 25]


In [119]:
#  vectorization
#  add
arr1 = np.array([1,2,3,4,5]) 
arr2 = np.array([2,3,4,5,6])

print(arr1+arr2)

[ 3  5  7  9 11]


In [122]:
# broadcasting 

print(arr + 5) # here behind the sence broadcasting has been perform it means adding the 5 to each value of array item
arr1 = np.array([1,2,3,4,5]) 
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])  # this is 2D array

print(arr1.shape) # it show the (1 row, 5 column)
print(arr2.shape) # it show 2 row and 5 column 
print(arr1 +arr2) # here it adding the all value to each at similar index number

[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 3  5  7  9 11]]


In [130]:
# normalization 

arr = np.array([[1,2],[3,4]])

print(np.mean(arr))
print(np.std(arr))

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev # this way we do array normalization
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [142]:
# mathematical function

# aggregation

arr = np.array([1,2,3,4,5])

print(arr)
print(np.sum(arr))
print(np.product(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr)) # variance

[1 2 3 4 5]
15
120
1
5
0
3.0
3.0
1.4142135623730951
2.0


In [145]:
# power function

arr = np.array([1,2,3,4,5])


print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [148]:
# log

arr = np.array([1,2,3,4,5])

print(np.log(arr)) # base is e
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [154]:
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [157]:
arr = np.array([1,2,3,4,5])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr)) # show the positive value

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
